Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [37]:
import numpy as np

def output_matrix(input_vector,increasing=True):
    N=len(input_vector) #calculating length of input_vector
    if increasing:
        result=[[pow(item,power) for power in range(0,N)] for item in input_vector] #matrix for increasing powers
        print(np.asanyarray(result))#using numpy function to output in matrix format
    else:
        result=[[pow(item,power) for power in range(N-1,-1,-1)] for item in input_vector] #matrix for decreasing powers
        print(np.asanyarray(result)) #using numpy function to output in matrix format

output_matrix([1,2,3,4])

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]


In [38]:
output_matrix([1,2,3,5],increasing=False)

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.


Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [83]:
def mov_avg(window_size):
    input_list = list(map(int,input().split())) #converting the input to list
    n   = len(input_list)
    k = 0
    
    for i in range(0,n-window_size+1): 
        sum = 0
        for j in range(i,window_size+i):
            sum += input_list[j] #calculating the sum according to the window size given as input
        k=k+1
        print("y"+str(k),"Moving average is : ",round(sum/window_size,2))
                   
mov_avg(int(input("Enter the window_size:")))

Enter the window_size:3
3 5 7 2 8 10 11 65 72 81 99 100 150
y1 Moving average is :  5.0
y2 Moving average is :  4.67
y3 Moving average is :  5.67
y4 Moving average is :  6.67
y5 Moving average is :  9.67
y6 Moving average is :  28.67
y7 Moving average is :  49.33
y8 Moving average is :  72.67
y9 Moving average is :  84.0
y10 Moving average is :  93.33
y11 Moving average is :  116.33
